# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat" # 'index' - это имя вашего серверного файла (index.ts)
  status = 200