[build]
  command = "npm install && npm run build"
  publish = "dist/public" 
  functions = "netlify/functions"
  
  # Web3Forms Access Key is a public key, safe to expose in frontend code
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_WEB3FORMS_ACCESS_KEY" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 

# Перенаправления
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server" 
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200