[build]
  command = "npm install && npm run build" # Можно оставить npm install для уверенности
  
  # ИСПРАВЛЕНИЕ: Указываем Netlify, что фронтенд находится в папке dist/public
  publish = "dist/public" 
  
  functions = "netlify/functions" 

# Перенаправления
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server" 
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200